### ISSUE TITLE
Headerstructuur + tekstkleur

### ISSUE THREAD

**Issue by anneke** [hay/magikal.nl#1]
Hoi,

Goed initiatief!

de header structuur klopt niet helemaal; als je de extra informatie nog niet hebt aangeklikt, heb je een pagina met een h1, h2, en h3 opeenvolgend, waarbij de h2 en de h3 eigenlijk paragrafen zouden kunnen zijn omdat ze de vraag van de h1 beantwoorden. Dit geldt sowieso voor de h3 (_ook als u nog geen brief heeft gehad_), die eigenlijk een stukje zin is die echt bij de h2 hoort. Ik zou dan ook dit veranderen in onderstaande, en dan met styling dezelfde opmaak maken:

```
<h2>
<span>Als u bent geboren in of vóór 1954 dan kunt u nú online een afspraak maken.</span>
<span>(ook als u geen brief heeft gehad)</span>
</h2>
```

Overigens is de kleur grijs van de "Ook als u geen brief heeft gehad" tekst te licht waardoor het slecht leesbaar is op de witte achtergrond.

**Comment by hay** [comment]
Hee Anneke,
dank, goede suggesties! Ik heb ze overgenomen.
